// SPDX-License-Identifier: Apache-2.0
#include "backends/ethernet/in_memory_transport.h"
#include "backends/ethernet/vspw_engine.h"

#include <assert.h>
#include <stdint.h>
#include <string.h>

typedef struct fake_runtime {
    uint64_t now_us;
} fake_runtime_t;

static uint64_t fake_now_us(void* context) {
    return ((fake_runtime_t*)context)->now_us;
}

static spw_result_t fake_delay_us(void* context,
                                  uint64_t delay_us,
                                  spw_timeout_us_t timeout_us) {
    fake_runtime_t* runtime = (fake_runtime_t*)context;
    if (timeout_us != SPW_TIMEOUT_INFINITE && timeout_us < delay_us) {
        return SPW_ERR_TIMEOUT;
    }
    runtime->now_us += delay_us;
    return SPW_OK;
}

static const spw_vspw_runtime_ops_t RUNTIME_OPS = {
    fake_now_us,
    fake_delay_us
};

static void make_peer(spw_transport_peer_id_t* peer, uint8_t id) {
    assert(spw_transport_peer_id_set(peer, &id, sizeof(id)));
}

static spw_vspw_engine_config_t make_config(uint32_t link_id,
                                            uint64_t nonce) {
    spw_vspw_engine_config_t config;
    memset(&config, 0, sizeof(config));
    config.link_id = link_id;
    config.fragment_payload_size = 512u;
    config.max_retries = 3u;
    config.ack_timeout_ms = 100u;
    config.keepalive_interval_ms = 1000u;
    config.peer_timeout_ms = 3000u;
    config.session_nonce = nonce;
    return config;
}

static void bring_up(spw_vspw_engine_t* a,
                     spw_vspw_engine_t* b) {
    spw_link_state_t state_a = SPW_LINK_ERROR_RESET;
    spw_link_state_t state_b = SPW_LINK_ERROR_RESET;

    assert(spw_vspw_engine_start(a) == SPW_OK);
    assert(spw_vspw_engine_start(b) == SPW_OK);

    assert(spw_vspw_engine_get_link_state(a, &state_a) == SPW_OK);
    assert(spw_vspw_engine_get_link_state(b, &state_b) == SPW_OK);
    assert(state_a == SPW_LINK_RUN);
    assert(state_b == SPW_LINK_RUN);
}

int main(void) {
    static spw_in_memory_transport_link_t link;
    spw_in_memory_transport_endpoint_t endpoint_a;
    spw_in_memory_transport_endpoint_t endpoint_b;
    spw_transport_provider_t provider_a = SPW_TRANSPORT_PROVIDER_INITIALIZER;
    spw_transport_provider_t provider_b = SPW_TRANSPORT_PROVIDER_INITIALIZER;
    spw_transport_peer_id_t peer_a = SPW_TRANSPORT_PEER_ID_INITIALIZER;
    spw_transport_peer_id_t peer_b = SPW_TRANSPORT_PEER_ID_INITIALIZER;
    fake_runtime_t runtime_state_a = {100u};
    fake_runtime_t runtime_state_b = {200u};
    spw_vspw_runtime_t runtime_a = {&RUNTIME_OPS, &runtime_state_a};
    spw_vspw_runtime_t runtime_b = {&RUNTIME_OPS, &runtime_state_b};
    spw_vspw_engine_config_t config_a = make_config(7u, 0x1111u);
    spw_vspw_engine_config_t config_b = make_config(7u, 0x2222u);
    static spw_vspw_engine_t engine_a;
    static spw_vspw_engine_t engine_b;
    uint8_t tx_data[1500];
    uint8_t rx_data[1500];
    spw_packet_t tx_packet;
    spw_packet_t rx_packet;
    spw_time_code_t tx_time_code = {17u, 0u};
    spw_time_code_t rx_time_code = {0u, 0u};
    spw_statistics_t stats_a;
    spw_statistics_t stats_b;
    size_t i;

    for (i = 0u; i < sizeof(tx_data); ++i) {
        tx_data[i] = (uint8_t)(i & 0xffu);
    }
    memset(rx_data, 0, sizeof(rx_data));

    spw_in_memory_transport_link_init(&link);
    make_peer(&peer_a, 0xa1u);
    make_peer(&peer_b, 0xb2u);

    assert(spw_in_memory_transport_endpoint_init(
               &endpoint_a, &link, 0u, &peer_a, &peer_b) == SPW_OK);
    assert(spw_in_memory_transport_endpoint_init(
               &endpoint_b, &link, 1u, &peer_b, &peer_a) == SPW_OK);
    spw_in_memory_transport_provider(&endpoint_a, &provider_a);
    spw_in_memory_transport_provider(&endpoint_b, &provider_b);

    assert(spw_vspw_engine_init(&engine_a, &config_a, &provider_a, &peer_b,
                                &runtime_a, NULL) == SPW_OK);
    assert(spw_vspw_engine_init(&engine_b, &config_b, &provider_b, &peer_a,
                                &runtime_b, NULL) == SPW_OK);

    bring_up(&engine_a, &engine_b);

    memset(&tx_packet, 0, sizeof(tx_packet));
    tx_packet.data = tx_data;
    tx_packet.length = sizeof(tx_data);
    tx_packet.capacity = sizeof(tx_data);
    tx_packet.terminator = SPW_TERMINATOR_EEP;

    memset(&rx_packet, 0, sizeof(rx_packet));
    rx_packet.data = rx_data;
    rx_packet.capacity = sizeof(rx_data);
    rx_packet.terminator = SPW_TERMINATOR_EOP;

    assert(spw_vspw_engine_send(
               &engine_a, &tx_packet, SPW_TIMEOUT_IMMEDIATE) == SPW_OK);
    assert(spw_vspw_engine_receive(
               &engine_b, &rx_packet, 1000u) == SPW_OK);
    assert(rx_packet.length == sizeof(tx_data));
    assert(rx_packet.terminator == SPW_TERMINATOR_EEP);
    assert(memcmp(rx_data, tx_data, sizeof(tx_data)) == 0);

    /* Process the ACK generated by engine B before the next logical TX. */
    {
        spw_link_state_t state = SPW_LINK_ERROR_RESET;
        assert(spw_vspw_engine_get_link_state(&engine_a, &state) == SPW_OK);
        assert(state == SPW_LINK_RUN);
    }

    assert(spw_vspw_engine_send_time_code(
               &engine_b, &tx_time_code, SPW_TIMEOUT_IMMEDIATE) == SPW_OK);
    assert(spw_vspw_engine_receive_time_code(
               &engine_a, &rx_time_code, 1000u) == SPW_OK);
    assert(rx_time_code.time_count == tx_time_code.time_count);
    assert(rx_time_code.control_flags == tx_time_code.control_flags);

    assert(spw_vspw_engine_get_statistics(&engine_a, &stats_a) == SPW_OK);
    assert(spw_vspw_engine_get_statistics(&engine_b, &stats_b) == SPW_OK);
    assert(stats_a.tx_packets == 1u);
    assert(stats_a.tx_bytes == sizeof(tx_data));
    assert(stats_a.eep_packets == 1u);
    assert(stats_a.rx_time_codes == 1u);
    assert(stats_b.rx_packets == 1u);
    assert(stats_b.rx_bytes == sizeof(tx_data));
    assert(stats_b.tx_time_codes == 1u);

    assert(spw_vspw_engine_stop(&engine_a) == SPW_OK);
    assert(spw_vspw_engine_stop(&engine_b) == SPW_OK);
    return 0;
}
